version: '3.3'

networks:
  database:
    internal: true
  api:
    internal: true
  monit:
  proxy:
services:
  db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
    expose:
      - 5432
    volumes:
      - /Users/flamengo
    networks:
      - database
  bot-wpp:
    container_name: bot-wpp
    image: qzzdocker24/bot-wpp:dev
    environment:
    - DATABASE=postgres
    - DB_HOST=postgres-db
    - DB_USER=postgres
    - DB_PASSWORD=12345
    - DB_PORT=5432
    - APP_NAME=bot-wpp
    - API_PORT=8080
    - SESSION_SECRET=gato preto
    - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DATABASE}
    networks:
      - api
      - database
    depends_on:
      - db
    healthcheck:
      test: "curl -sS http://bot-wpp:8080/health"
      interval: 1s
      timeout: 30s
      retries: 6
  proxy-bot-wpp:
    image: nginx
    container_name: proxy-bot-wpp
    restart: unless-stopped
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    ports:
      - '80:80'
    networks:
      - api
      - proxy
    depends_on:
      - bot-wpp
  prometheus-bot-wpp:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus-bot-wpp
    restart: unless-stopped
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infra/prometheus/alert.rules:/etc/prometheus/alert.rules
      - ./infra/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console.libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      - api
      - monit
    depends_on:
      - proxy-bot-wpp
  alertmanager-bot-wpp:
    image: prom/alertmanager
    container_name: alertmanager-bot-wpp
    volumes:
      - ./infra/alertmanager:/etc/alertmanager/:ro
    ports:
      - 9093:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    networks:
      - monit
    depends_on:
      - prometheus-bot-wpp
  grafana-bot-wpp:
    image: grafana/grafana
    container_name: grafana-bot-wpp
    restart: unless-stopped
    volumes:
      - ./infra/grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    networks:
      - monit
    depends_on:
      - alertmanager-bot-wpp

